version: 2

jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - store_artifacts:
          path: test/videos
      - store_artifacts:
          path: test/screenshots


  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx firebase use --token $FIREBASE_KEY $TARGET_ENVIRONMENT
      - run: npx firebase deploy --token $FIREBASE_KEY

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
